/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WareHouse_System;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class E_update extends javax.swing.JFrame {

     Connection con=null;
   ResultSet rs=null;
   PreparedStatement pst=null;
   Statement stmt = null;
    private Object s;/** 
    
    
    
    /**
     * Creates new form Products
     */

    /**
     * /**
 Creates new form Products
     * @throws java.sql.SQLException
     */
    public E_update() throws SQLException{ 
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
      Statement statement = null;    
     try{
     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    Connection connn;
         connn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Ware_House;user=raheels;password=1234567;");
         statement = connn.createStatement();
  
     System.out.println("Connected to database !");
   }
   catch(SQLException sqle) {
    System.out.println("Sql Exception :"+sqle.getMessage());
   }
   catch(ClassNotFoundException e) {
   System.out.println("Class Not Found Exception :" + e.getMessage());
  }  
     ResultSet rss = statement.executeQuery("select * from Employee");
     ResultSetMetaData  rsmetadata = rss.getMetaData();
        
    int columns = rsmetadata.getColumnCount();    
 DefaultTableModel dtm = new DefaultTableModel(); 
   Vector c_name = new Vector(); 
   Vector r_name = new Vector();    
        
  for(int i=1;i<columns;i++){
      c_name.addElement(rsmetadata.getColumnName(i));
  }      
        dtm.setColumnIdentifiers(c_name);   
        while(rss.next()){
            r_name = new Vector();
             for(int j=1;j<columns;j++){
     r_name.addElement(rss.getString(j));
  }    
    dtm.addRow(r_name);                    
        }
            mytable2.setModel(dtm);     
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mytable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ha = new javax.swing.JTextField();
        jd = new javax.swing.JTextField();
        mn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comission = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ci = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        co = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        mon = new javax.swing.JTextField();
        en = new javax.swing.JTextField();
        bs = new javax.swing.JTextField();
        os = new javax.swing.JTextField();
        exd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(103, 589, 55, 23);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(4, 4, 64));
        update.setText("updated");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(1000, 490, 170, 40);

        mytable2.setBackground(new java.awt.Color(51, 51, 255));
        mytable2.setForeground(new java.awt.Color(255, 255, 255));
        mytable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18"
            }
        ));
        jScrollPane1.setViewportView(mytable2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1370, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("commission");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 500, 120, 14);
        jPanel1.add(fn);
        fn.setBounds(330, 210, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("join date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1160, 250, 50, 14);
        jPanel1.add(ha);
        ha.setBounds(110, 290, 420, 30);
        jPanel1.add(jd);
        jd.setBounds(1220, 240, 130, 30);
        jPanel1.add(mn);
        mn.setBounds(470, 210, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 220, 40, 14);
        jPanel1.add(comission);
        comission.setBounds(110, 490, 130, 30);
        jPanel1.add(ln);
        ln.setBounds(610, 210, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("detno");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(770, 250, 50, 14);
        jPanel1.add(dn);
        dn.setBounds(810, 240, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("birthday");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(960, 250, 50, 14);
        jPanel1.add(bd);
        bd.setBounds(1020, 240, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("emp no");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 220, 50, 14);
        jPanel1.add(eid);
        eid.setBounds(110, 210, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("country");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 300, 90, 14);
        jPanel1.add(sa);
        sa.setBounds(110, 250, 420, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("street address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 260, 90, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("city");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(560, 260, 90, 14);
        jPanel1.add(ci);
        ci.setBounds(610, 250, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("house address");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 300, 90, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("phone number");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 340, 90, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("mobile number");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(250, 340, 90, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("emergency number");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(490, 340, 120, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("basic salary");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 380, 120, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("overtime salary");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 420, 120, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("extra day");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 460, 120, 14);
        jPanel1.add(co);
        co.setBounds(610, 290, 130, 30);
        jPanel1.add(pn);
        pn.setBounds(110, 330, 130, 30);
        jPanel1.add(mon);
        mon.setBounds(340, 330, 130, 30);
        jPanel1.add(en);
        en.setBounds(610, 330, 130, 30);
        jPanel1.add(bs);
        bs.setBounds(110, 370, 130, 30);
        jPanel1.add(os);
        os.setBounds(110, 410, 130, 30);
        jPanel1.add(exd);
        exd.setBounds(110, 450, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   Employee s= new Employee();
           s.setVisible(true);
           dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
  Statement stmt2 = null;    
     try{
     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    Connection nn;
         nn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=chase_up;user=raheel;password=1234567;");
         stmt2 = nn.createStatement();
  
     System.out.println("Connected to database !");
   }
   catch(SQLException sqle) {
    System.out.println("Sql Exception :"+sqle.getMessage());
   }
   catch(ClassNotFoundException e) {
   System.out.println("Class Not Found Exception :" + e.getMessage());
  }  
        
      if(    ((eid.getText()== null || eid.getText().isEmpty()))
      || ((fn.getText()== null || fn.getText().isEmpty()))
     || ((mn.getText()== null || mn.getText().isEmpty()))
     || ((ln.getText()== null || ln.getText().isEmpty()))
     || ((dn.getText()== null || dn.getText().isEmpty()))
     || ((bd.getText()== null || bd.getText().isEmpty()))
     || ((jd.getText()== null || jd.getText().isEmpty()))
     || ((sa.getText()== null || sa.getText().isEmpty()))
     || ((ha.getText()== null || ha.getText().isEmpty()))
     || ((ci.getText()== null || ci.getText().isEmpty()))
     || ((pn.getText()== null || pn.getText().isEmpty()))
     || ((mon.getText()== null || mon.getText().isEmpty()))
     || ((en.getText()== null || en.getText().isEmpty()))
     || ((bs.getText()== null || bs.getText().isEmpty()))
     || ((os.getText()== null || os.getText().isEmpty()))
     || ((exd.getText()== null || exd.getText().isEmpty()))
      || ((comission.getText()== null || comission.getText().isEmpty()))
             
             )     
     
     
     
     
     
     
     {
       JOptionPane.showMessageDialog(null,"Please insert Complete Information!!!!!!!!!!!!1");
       eid.setText(null);
       fn.setText(null);
     mn.setText(null);
  ln.setText(null);
  dn.setText(null);
  bd.setText(null);
  jd.setText(null);
  sa.setText(null);
  ha.setText(null);
 ci.setText(null);
   comission.setText(null);
 pn.setText(null);
  mon.setText(null);
  en.setText(null);
     bs.setText(null);
     os.setText(null);
   exd.setText(null);
     comission.setText(null);
             
     }
          
     else {
               try{
          String q = "update Employee set first_name='"+fn.getText()+"',middle_name='"+mn.getText()+"',last_name='"+ln.getText()+"',dept_no='"+dn.getText()+"',birthday='"+bd.getText()+"',joining_date='"+jd.getText()+"',street_address='"+sa.getText()+"',house_address='"+ha.getText()+"' ,city='"+ci.getText()+"',country='"+co.getText()+"',phone_no='"+pn.getText()+"',mobile_no='"+mon.getText()+"',emergency_no='"+en.getText()+"',basic_salary='"+bs.getText()+"' ,overtime_salary='"+os.getText()+"',extra_day='"+exd.getText()+"' ,commission='"+comission.getText()+"' where  emp_no="+eid.getText()+""; 
          stmt2.execute(q);
          
          JOptionPane.showMessageDialog(null," Added to the Dtabase");
          eid.setText(null);
       fn.setText(null);
     mn.setText(null);
  ln.setText(null);
  dn.setText(null);
  bd.setText(null);
  jd.setText(null);
  sa.setText(null);
  ha.setText(null);
 ci.setText(null);
 co.setText(null);
 pn.setText(null);
  mon.setText(null);
  en.setText(null);
     bs.setText(null);
     os.setText(null);
   exd.setText(null);
   comission.setText(null);
         
           
      }
    catch(SQLException ex) {   
        JOptionPane.showMessageDialog(null, ex.toString());
        
    }  
    }                         
        
        
        
        
        
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new E_update().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(E_update.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bd;
    private javax.swing.JTextField bs;
    private javax.swing.JTextField ci;
    private javax.swing.JTextField co;
    private javax.swing.JTextField comission;
    private javax.swing.JTextField dn;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField en;
    private javax.swing.JTextField exd;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField ha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jd;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mn;
    private javax.swing.JTextField mon;
    private javax.swing.JTable mytable2;
    private javax.swing.JTextField os;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField sa;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
